version: '3'

# Before supabase/postgres 14.1.0
services:
  db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

# supabase/postgres 14.1.0 and beyond
services:
  db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf 
    environment:
      POSTGRES_PASSWORD: postgres