version: "3.6"

# minio
services:
  minio:
    image: minio/minio:RELEASE.2023-05-04T21-44-30Z
    container_name: minio
    restart: always
    command: ["server", "--console-address", ":9001", "/data"]
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    volumes:
      - minio_data:/data

volumes:
  minio_data:
    driver: local
