kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app-label
  template:
    spec:
      containers:
        - env:
            - name: YOUR_ENV_VARIABLE
              value: your-env-value
          name: your-container-name
          image: your-container-image
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
    metadata:
      labels:
        app: your-app-label
metadata:
  name: your-deployment-name
  labels:
    app: your-app-label
apiVersion: apps/v1
